import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDIYy1cEoJIzN4VacqPuC8pV66I1wjVzg&v=beta&libraries=places"
          strategy="beforeInteractive"
        />
      </head>
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
